### ISSUE TITLE
Re-dockerize everything

### ISSUE THREAD

**Issue by mrjones-plip** [medic/chis-interoperability#11]
After all services are culled per medic/chis-interoperability#8  and hardened in medic/chis-interoperability#9 , we might consider publishing updated docker images (or at least Dockerfiles) that incorporate all the changes we made into an easy to set up system.

**Comment by f-odhiambo** [comment]
We can also look into the Kubernetes option listed in the Instant OpenHIE setup docs on GitHub https://github.com/openhie/instant

**Comment by mrjones-plip** [comment]
Thanks for the tip @f-odhiambo! 

Now that we're revisiting this ticket, and reviewing the work we did [to document on how we set it up](https://github.com/medic/chis-interoperability/), I feel that maybe this ticket is complete!  Following the thought of "If it is not broken, don't fix it" and given our instance has now been stable for some weeks, I'm going to close this ticket.  If anybody feels this is a bad idea, please re-open!
