### ISSUE TITLE
Backup MongoDB

### ISSUE THREAD

**Issue by mrjones-plip** [medic/chis-interoperability#14]
@nsikak-e-akpakpan said:

>    Have we set up backup and restore process for the mongo db content in case there if failure and there is a need to reset the container?  This may be critical to do so that we do not loose info if the server acts up. 

We should deploy a backup solution, including documentation.  We should then test that we can recover from data loss.

**Comment by f-odhiambo** [comment]
Picking up this issue @mrjones-plip

**Comment by mrjones-plip** [comment]
Closing to focus on other issues which are deemed higher priority
