### ISSUE TITLE
Add valid TLS certificate to heartbeat

### ISSUE THREAD

**Issue by mrjones-plip** [medic/chis-interoperability#23]
Currently, when you log in to the [OpenHIIM Admin console](https://cop.app.medicmobile.org:9001), you need to first visit the [heartbeat URL](https://cop.app.medicmobile.org:8080/heartbeat) on the openhim-core to accept the self signed certificate.  You can then go back to the log in form and it should work.  However, Chrome is no longer letting users bypass this self signed cert.  

We should do **one of** the following:
1. configure a valid TLS certifcate on the server running on port 8080 in the `openhim-core`  container. This would likely mean mounting the `/etc/letsencrypt/` directory in the  `openhim-core` container like we do with the `nginx-proxy` 
1. extend the reverse proxy running in `nginx-proxy` to have a new vhost and change the OpenHIM configuration to use this new URL:PORT combo.

Helpful info:
* TLS certs for `cop.app.medicmobile.org` are in `/etc/letsencrypt/live/cop.app.medicmobile.org/*`
* The  `nginx-proxy` container has the certificates already mounted in it per [the container config](https://github.com/medic/chis-interoperability/blob/5c4855cd0f85fe9be957d3df704c7c33befa22e4/docker/docker-compose.yml#L54).

**Comment by mphomollo** [comment]
> 1.	Verified we have /etc/letsencrypt/live directory but do not have the permission to inspect the content
> 2.	Checked the core container and did not see letsencrypt host directory mounted, for some reason, I do not have the permission to mount it.  We may need to add the volume to the docker-compose script
> 3.	Also checked the Nginx, and did not see the config for the reverse proxy in the sites-enabled or sites-available.  I just wanted to confirm that you still think this is an option to pursue
> 4.	Per my review of the documentation, it seems allowing wide-open access to developers/administrators without shell access would not be necessary. If that is the case, we should be able to continue to access the OpenHIM console via SSL tunnel with self-signed certificates
> 5.	Can you confirm whether the root@openhim.org password was changed? I am getting incorrect credentials when I use the default password.

I will schedule a check-in on this issue this week.  Thanks.

**Comment by mrjones-plip** [comment]
@mphomollo  and @nsikak-e-akpakpan  - thanks for the call today!

Here's some follow up notes:

> Verified we have /etc/letsencrypt/live directory but do not have the permission to inspect the content

This is fixed as `mpho` user now has `sudo` perms

> Checked the core container and did not see letsencrypt host directory mounted, for some reason, I do not have the permission to mount it. We may need to add the volume to the docker-compose script

We decided to fix it another way!  We'll use the reverse proxy in `nginx-proxy` container.

> Also checked the Nginx, and did not see the config for the reverse proxy in the sites-enabled or sites-available. I just wanted to confirm that you still think this is an option to pursue

This was in the `nginx-proxy` container:

```
CONTAINER ID   IMAGE                        COMMAND                  CREATED       STATUS         PORTS                                                                                                                                     NAMES
a20eceb102fd   nginx:latest                 "/docker-entrypoint.…"   3 hours ago   Up 2 minutes   0.0.0.0:5002->5002/tcp, :::5002->5002/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:9001->9001/tcp, :::9001->9001/tcp   nginx-proxy
```

> Per my review of the documentation, it seems allowing wide-open access to developers/administrators without shell access would not be necessary. If that is the case, we should be able to continue to access the OpenHIM console via SSL tunnel with self-signed certificates

I think this is resolve too?  If not let me know, but OpenHIM remains open on port 9001, but HAPI FHIR is only accessible with the SSH tunnel. See the ["Services" section](https://github.com/medic/chis-interoperability#services) for more info where services are located.

> Can you confirm whether the root@openhim.org password was changed? I am getting incorrect credentials when I use the default password.

I can! As part of the securing the instance, I created new passwords and then shared them in a file on the `cop` server.  To see them, log into the server and run: `sudo cat ~root/logins.txt`

**Comment by mrjones-plip** [comment]
@mphomollo  - Here was our plan to fix the certs on port 8080:

1. remove port mapping on `core` container for `8080:8080`
2. add port mapping on `nginx-proxy` container for `8080:8080`
3. Add reverse proxy for `nginx-proxy` in the `/etc/nginx/nginx.conf` to route traffic from `https://cop.app.medicmobile.org:8080`  to `https://core:8080`.

We got steps 1 and 2 working, but got stuck on the 3.  This was because we were missing the `ssl_verify_client off;` line in the 3rd `server` we added the config.  Once I did this, and restarted the container - it's working now!

So - to make this ticket complete - the outstanding work is to:
1. create a branch to this repo (likely you'll have to fork this repo and create a branch there)
1. review the changes to the `docker-compose.yml` file and commit them to your repo
1. review the changes to `nginx.conf` and commit them to your repo
2. update the `readme.md` with changes, if needed
2. open a pull request to get our changes merged to `main` on this repo
3. deploy to production with a `git pull origin` and a `./compose.sh up`

I'm available to help with any of these!

**Comment by mrjones-plip** [comment]
I believe all this is complete! As well I, I updated the documentation to be complete in #29 when updating the docs on how to deploy the new Node container for that PR.

@mphomollo  - if I missed anything feel free to re-open or let me know and I can file a new ticket.
