### ISSUE TITLE
Move FHIR folder from visualizations repo to interoperability repo

### ISSUE THREAD

**Issue by michaelkohn** [medic/chis-interoperability#3]
When we started the interoperability project, we didn't have a repo set up yet so we put our [FHIR samples](https://github.com/medic/chis-visualizations/tree/main/FHIR) in the [visualizations](https://github.com/medic/chis-visualizations) repo. We should move these to the [interoperability](https://github.com/medic/chis-interoperability) repo now. 

So the ask is.... move this [folder](https://github.com/medic/chis-visualizations/tree/main/FHIR) to [this](https://github.com/medic/chis-interoperability) repo.

**Comment by mrjones-plip** [comment]
[done](https://github.com/medic/chis-interoperability/tree/master/FHIR)!
