### ISSUE TITLE
[CHT] Update outbound config for the FHIR Patient endpoint

### ISSUE THREAD

**Issue by michaelkohn** [medic/chis-interoperability#5]
Right now the outbound [config](https://github.com/medic/chis-interoperability/blob/d6e95a5223d0137112d2f9696da4f0f0033b4656/cht-config/app_settings.json#L363-L395) we created for https://github.com/medic/chis-interoperability/issues/1 sends any record with `"relevant_to": "doc.type === 'person'"`. The next FHIR resource we are going to send is the [Practitioner](http://www.hl7.org/fhir/practitioner.html), which is _also_ a `person`, so we should make some updates. 

To prepare for this, I think we should do the following

- [x] Update `relevant_to` to only send if the Role has been set and it's been set to Patient (see below)
- [x] We should probably rename the [config](https://github.com/medic/chis-interoperability/blob/d6e95a5223d0137112d2f9696da4f0f0033b4656/cht-config/app_settings.json#L363) from `FHIR` to `FHIR_patient`

<img width="612" alt="Screen Shot 2021-04-15 at 1 07 58 PM" src="https://user-images.githubusercontent.com/10096985/114859923-a4a3b680-9deb-11eb-8d9d-643b80d60454.png">

**Comment by mrjones-plip** [comment]
After creating a new config (see 6476d8cfb1f7660b2db691a6392c998b35a71cfd), I then updated CHT instances with this `medic-conf` call:

```
medic-conf --url=https://medic:CHT_PASSWORD_HERE@cht-cop-interop.dev.medicmobile.org/ compile-app-settings backup-app-settings upload-app-settings
```

Now only `Role` of type `patient` will get pushed to OpenHIM.  Further, config is now named `FHIR_patient`. 

@michaelkohn  - another thing that should Just Work upon  your return!
