### ISSUE TITLE
Invalid username and password for root@openhim.org at OpenHIM Console 

### ISSUE THREAD

**Issue by nsikak-e-akpakpan** [medic/chis-interoperability#6]
@f-odhiambo, @mrjones-plip -- Need to troubleshoot the issue this morning with invalid Username and password for the OpenHIM Console at cop.app.medicmobile.org:9000.  @f-odhiambo, you have done this install before so it would be great if you work with @mrjones-plip to get this done.  Here are steps to follow:

- @mrjones-plip -- please confirm you did not change the root@openhim.org password
- if did not change, clear your browser cache, retry login
- check instant-openhim site for info on how to address this issue
- if no info, restart the openhim-console container and retry
- if that does not work, destroy the instant-openhie setup
- confirm that all the containers have been removed, if not remove all the container
- rerun the installation from the /srv/instant directory, see readme on the instant-openhie git repo or in the /instant directory
- once the installation is complete, enter the openhim-console container, cd /config, modify config.json localhost to cop.app.medicmobile.org
- retry login using root@openhim.org/instant101
- add new users to the console, so we do not need to root user for access

**Comment by mrjones-plip** [comment]
After seeing that it's trying to GET in the dev console to `https://cop.app.medicmobile.org:8080/authenticate/root@openhim.org`, I saw that indeed you need to go to that URL and accept the invalid cert first. 

After doing that, I get a new error "could not find user".  You can see this with the `curl` test call:

```
➜  ~ curl -k https://cop.app.medicmobile.org:8080/authenticate/root@openhim.org
Could not find user by email root@openhim.org%  
```

**Comment by mrjones-plip** [comment]
Hopefully this has been solved! Fix was to redo the deployment using `docker-compse` and to redo some of the initialization scripts originally in Instant OpenHIE. All changes are now in this repo.
