### ISSUE TITLE
Skin or theme cop server

### ISSUE THREAD

**Issue by mrjones-plip** [medic/chis-interoperability#7]
After all the dust has settled in medic/chis-visualizations#7 and medic/chis-visualizations#8  (and possibly medic/chis-visualizations#9 and medic/chis-visualizations#10), we should ensure all web GUIs are skinned and themed with logos and slogans accordingly.

**Comment by f-odhiambo** [comment]
Got some resourcing for this. I have an SRE eng available for for an LOE total of 1/2 day to go through any technical issue I may have on request

**Comment by mrjones-plip** [comment]
@f-odhiambo  - sounds good! If I had a choice, I'd say that the [two backup tickets](https://github.com/orgs/medic/projects/81) would be a better choice to do next, but it all needs to be done!

What ever you do for this skinning/theming effort, we should be sure to either commit any changes in a GH repo, or update GH readmes - or both!

**Comment by f-odhiambo** [comment]
This has been deprioritized will pick up one of the backup issues cc. @mrjones-plip

**Comment by mrjones-plip** [comment]
Closing to focus on other issues which are deemed higher priority
